name: Check competitor prices

on:
    schedule:
        # Runs every 6 hours
        - cron: '0 0,6,12,18 * * *'
        workflow_dispatch: # Allows manual triggering

jobs:
    check-prices:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Set up Python
            uses: actions/setup-python@v5
            with:
                python-version: '3.10'
                cache: 'pip'

          - name: Install depencies
            run: |
              python -m pip install --upgrade pip
              pip install requirements.txt

          - name: Run price checker
            env:
              FIRECRAWL_API_KEY: ${{ secrets.FIRECRAWL_API_KEY }}
              POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
            run: python src/check_prices.py